### ISSUE TITLE
v5.1.2 backwards compatibility, and unpublished version.

### ISSUE THREAD

**Issue by patsjo** [ahmadnassri/node-har-validator#112]
Between 5.1.1 and 5.1.2 the package.json changed version of ajv from ^5.3.0 to ^6.5.5.

When some other package (like request 2.88.0) has a dependency of har-validator ~5.1.0, it can cause other things to break if you allow a major dependency change, without changing you own major version.

In my case, I cant build any more. I got the error:
ERROR in bundle-a54549f6346a118c4764.js from UglifyJs
SyntaxError: Unexpected token: name (length) [./~/punycode/punycode.js:55,0]

This error is because ajv from version 5.x.x to 6.x.x. forced punycode to change major version aswell. (nothing wrong with that)

**Comment by ahmadnassri** [comment]
interesting, I'm going to dig into this today, and see what can be done.

**Comment by ahmadnassri** [comment]
I have unpublished `5.1.2` and `5.1.1` in the meantime from npm. future installs of `request` should not be affected.

**Comment by ahmadnassri** [comment]
@patsjo can you please provide me with some reproducible steps?

**Comment by mattcasey** [comment]
Hi, this error is breaking one of our builds. It just started happening within the last 24 hours. I can reproduce just by doing `npm install ajv`. Using npm 6

**Comment by mattcasey** [comment]
OK, I figured it out on our end. It just so happened that we needed to bump a dependency and update our package-lock.json at the moment that 5.1.2 was available. I fixed the issue for us by just deleting package-lock.json and re-creating with `npm install`. I can share our lock file if you want, but it is pretty massive.

**Comment by simoami** [comment]
@ahmadnassri 

Need to let you know the impact of unpublishing on dependent libs. It's failing a yarn install. 

```
yarn
yarn install v1.7.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "http://..../har-validator/-/har-validator-5.1.2.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/code/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Our dependencies are:

=> Found "strong-remoting#har-validator@5.1.2"
=> Found "loopback#har-validator@5.1.2"
=> Found "loopback-connector-remote#har-validator@5.1.2"
=> Found "npm-registry-client#har-validator@5.1.2"

As a strategy, I'd perhaps suggest you either bump to a 5.1.3 that reverts the bad behavior or to republish 5.1.1 and 5.1.2 as copies of 5.1.0 so we don't get a 404 error on yarn/npm install, because of fixed dependencies in *.lock files

**Comment by nickf829** [comment]
Publishing a rolled back v5.1.3 would have been preferred to unpublishing 5.1.2.  This is causing major headaches from nexus and artifactory users.

**Comment by sledorze** [comment]
unpublishing 5.1.2 has caused an outage on our circle-ci tests, please, release a 5.1.3 version before the whole universe goes mad about you! :)

**Comment by aaronhayes** [comment]
Also seeing 404 errors during installs; Ideally we should be releasing a`5.1.3` version that reverts broken code. This is going to cause a lot of people headaches; this package gets around ~10m downloads per week.

**Comment by Paqrat76** [comment]
@ahmadnassri Can you give folks an update as to your plan/timing to resolve this issue?

**Comment by Paqrat76** [comment]
Here is what is blocking our builds:
`npm ERR! notarget No matching version found for har-validator@5.1.2`

$ npm list har-validator
snowbucket@1.2.3 /mnt/c/DevGit/snowbucket
├─┬ jest@23.6.0
│ └─┬ jest-cli@23.6.0
│   └─┬ jest-environment-jsdom@23.4.0
│     └─┬ jsdom@11.12.0
│       └─┬ request@2.88.0
│         └── har-validator@5.1.0
└─┬ snowflake-sdk@1.1.8
  └─┬ request@2.88.0
    └── har-validator@5.1.2

**Comment by ahmadnassri** [comment]
I'm investigating the issue, so far nobody has provided me with any reproducible steps.

`request` is dependant on version [`~5.1.0`](https://github.com/request/request/blob/master/package.json#L37)

`npm install request`  correctly installs the latest matching version from npm:

```plain
$ npm install request
$ npm list har-validator
/tmp
└─┬ request@2.88.0
  └── har-validator@5.1.0
```

there was never any broken code pushed or changes made, other than bumping `ajv`, which, despite being a major version, still has no impact on `har-validator` or `request`

**Comment by ahmadnassri** [comment]
cc: @realityking

**Comment by ahmadnassri** [comment]
for folks with cached `package-lock` / `yarn.lock` run `install` action again to update your lock files.

@patsjo what version of node are you on?

**Comment by ahmadnassri** [comment]
for reference, this is the only change between `5.1.0` and `5.1.2` of any meaningful impact: https://github.com/ahmadnassri/node-har-validator/commit/759bffea49e473b07cc9e623afbd27ef1fb7418f#diff-6230eb7fbf1dd2186bf1be6042c27f55 _(the rest are docs and dotfiles)_

ajv version got bumped and related changes were added, nothing else was changed, and ajv still maintains support for `browsers and Node.js 0.10-8.x` according the [README](https://github.com/epoberezkin/ajv/blob/master/README.md)

cc: @epoberezkin

**Comment by realityking** [comment]
AJV’s readme is wrong. It only supports Node.js 6 https://github.com/ahmadnassri/node-har-validator/pull/109#issuecomment-401607223

As for har-validator itself, the CircleCI config should be amended to cover all supported versions so something like this doesn’t happen.

Best thing right now would probably be to rerelease 5.1.0 as 5.1.3 and 5.1.2 as 6.0.

**Comment by marcusmotill** [comment]
# Please publish a rolled back v5.1.3
the unpublished package is causing all sorts of issues very ill-advised

**Comment by seprich** [comment]
`npm install` works creating a package-lock.json file where har-validator is resolved to 5.1.3 (required by request@2.88.0). However `yarn install` fails with:
> error Couldn't find any versions for "har-validator" that matches "5.1.2"

So yarn seeks metadata from https://yarnpkg.com  and clearly the "unpublishing" hasn't reached there.
I would kindly request if @ahmadnassri could do something to fix yarn metadata.

**Comment by seprich** [comment]
Yes `npm install` works, resolving har-validator to version 5.1.3 (as required by request@2.88.0).
However `yarn install` is broken because it fetches metadata from https://registry.yarnpkg.com \:
> error Couldn't find any versions for "har-validator" that matches "5.1.2"

Seems that the unpublishing has left yarn registry dirty.

**Comment by ahmadnassri** [comment]
I don't / can't support `yarn`, they seem to be doing their own snowflake thing ... 

> for people using `yarn` because of the speed, `npm` has made massive improvements in recent versions and is actually faster than `yarn` now, see `npm ci`, `pacakge-lock.json`, `npm install` improvements, etc ...  _(just FYI)_

They also don't have any method of interacting with their registry to do things like unpublish: https://github.com/yarnpkg/yarn/issues/4746

unpublishing packages is part of the expected behavior of a registry, and of dependency management.

a registry or registry client does not take care of managing your dependencies for you, you still have to do your part in managing your dependencies in your apps.

@seprich also see these issues with Yarn that are going on unresolved: https://github.com/yarnpkg/yarn/issues/5212

I'm sorry, but `yarn` is not an official registry, and my packages (as well as all of npm's users packages) are targeted for publish on `npm`, which means we follow and support npm's workflows.

**Comment by ahmadnassri** [comment]
also, see conversation thread here: https://twitter.com/AhmadNassri/status/1062733707579219968

it might just be that your lock files need to be updated @seprich

**Comment by amypellegrini** [comment]
Hi @ahmadnassri, I encounter this bug today, reproduction steps:

In a Mac, using yarn, tried to install `react-markdown` was enough to see the error.

Hope it helps! I'll try to spare some time to give a hand if I can.

**Comment by ahmadnassri** [comment]
hey @amypellegrini 

the issue is in your lock file, likely needs a refresh, installation works fine without a lock file, so there must be a conflict in there.

![image](https://user-images.githubusercontent.com/183195/48629126-d1d3ac80-e986-11e8-8852-44c91bf7b199.png)

**Comment by Pipeman** [comment]
@ahmadnassri It sound strange it is related only to package-lock, I went all the way down to delete the entire node installation and it was still happening. Only when I manually npm installed har-validator 5.1.3 as a direct dependency I was able to solve the issue.

**Comment by ahmadnassri** [comment]
@Pipeman I don't disagree, but I cannot help or control what's happening in the dependency chain and module resolution logic in yarn / npm.

my understanding is anybody having these issues *must have had their lock files updated* between `5.1.0` and `5.1.2`, _(`5.1.1` was published moments before `5.1.1`  so i'm skipping that in this context)_ which subsequently when `5.1.2` was deleted, lead to this conflict.

so my question is to people: Why and how are you updating your lock files, and why is updating lock files after that fact is not an acceptable answer?

I'm tempted to just release a `5.1.2` and `5.1.1` duplicates of `5.1.0` to stop the noise. but honestly, I'm baffled to how broken the yarn process is here and how badly lock files are misunderstood!

**Comment by pgonzal** [comment]
> And yes, it is trivial to fix the lockfile

For a serious production application, it's important to be able to go back and reinstall/rebuild old release branches from Git.  In these situations, nontrivial effort may be required to update the lockfile.

> Re: the temptation, you cannot republish over an unpublished tag on npm.

You could probably email `support@npmjs.com` and see if they could un-unpublish `5.1.2`, i.e. restoring the tarball with its exact original bytes.

**Comment by ahmadnassri** [comment]
@mklopets all valid points. I started this topic with Yarn team to deep dive into this more: https://github.com/yarnpkg/yarn/issues/6694

I'm now questioning how this all unfolded ... did people really refresh their lock files specifically affecting `request`/`har-validator` in the short amount of time between publishing and unpublishing? that somehow seems contrary to what people here are describing their workflow to be ...

namely as @pgonzal mentioned, seems like you are relying on lock files to keep version dependencies locked down, yet somehow you are also getting then updated somewhere in your workflow ... 

this is very confusing and a conflicting message from what's being described by users.

**Comment by ahmadnassri** [comment]
Timeline of events:

event      | version | date  
---------- | ------- | ---
publish    | 5.1.1   | Nov 6 @ 9:02 PM EST
publish    | 5.1.2   | Nov 6 @ 9:04 PM EST
un-publish | 5.1.1   | Nov 9 @ 9:35 AM EST
un-publish | 5.1.2   | Nov 9 @ 9:36 AM

**Comment by sandeeptharayilGit** [comment]
This happened to me as well. 
Delete `package-lock.json` and rerun `npm i` to fix the issue

**Comment by ahmadnassri** [comment]
@sandeeptharayilGit can you help me validate my theory? did this project get initiated between Nov 6 and Nov 9? or was it there before and had a `package-lock.json` already?

**Comment by mklopets** [comment]
@ahmadnassri in my case specifically, I setup a new codebase some time last week, which is when the subdependency got added to our code.

@pgonzal I'm having a hard time seeing why one couldn't take an old commit/branch and apply a lockfile update to that (not trying to be smart here, just not understanding). In many "serious production system" cases, previous builds can be redeployed anyway, with no need to involve yarn.

**Comment by ahmadnassri** [comment]
thanks @mklopets this helps validate my thinking.

**Comment by sandeeptharayilGit** [comment]
@ahmadnassri.  This wasn't breaking in my local machine for last few weeks. When I took a build in jenkis with this new package-lock file, it broke there. It breaking even now.
Inorder to replicate the issue in my local, I deleted node_modules folder and cleaned npm cache but used the same lock file.

It got fixed when I deleted lock file.

Hope this helps you

**Comment by sandeeptharayilGit** [comment]
@ahmadnassri.  This wasn't breaking in my local machine for last few weeks. When I took a build in jenkis with this new package-lock file, it broke there. It breaking even now.
Inorder to replicate the issue in my local, I deleted node_modules folder and cleaned npm cache but used the same lock file.

It got fixed when I deleted lock file.

Hope this helps you

**Comment by pgonzal** [comment]
> I'm having a hard time seeing why one couldn't take an old commit/branch and apply a lockfile update to that (not trying to be smart here, just not understanding). In many "serious production system" cases, previous builds can be redeployed anyway, with no need to involve yarn.

@mklopets Suppose we're backporting a critical security fix.  There may be 10 different old branches that need to be fixed and released. Some of these branches may be more than a year old, (e.g. for a previous product release) and could be using old tooling or a different package manager. The policy for fixing these branches would be "minimal fix", i.e. change as little as possible to fix the security issue while minimizing the risk of introducing a regression.  When we go to build the fixed branch and encounter the **har-validator** error, we need to somehow fix up the **shrinkwrap.yaml** or **package-lock.json** or **yarn.lock** or **npm-shrinkwrap.json** (depending on the package manager). The safest way would be to edit that file manually, to ensure that only that one version number is changed. But the person approving the PR is going to have questions about that... How did you prove that 5.1.2 and 5.1.3 don't have any code changes, if we can't obtain 5.1.2 any more? Why is it safe to manually edit this machine-generated file? What do we need to test?

It's not difficult, just tedious, particularly if there are multiple release branches.

**Comment by pgonzal** [comment]
BTW I was wondering why we didn't hit these issues more broadly.  It turns out that our production systems use a caching proxy to obtain NPM packages. I can actually still run `npm install har-validator@5.1.2` successfully in those environments, since it's not unpublished from the proxy feed.  Seems this is mostly just affecting our public GitHub repos.

**Comment by DAlperin** [comment]
Hey there I do not often use yarn but I am trying to use a tool that depends on it and I am wondering if anyone has come up with a concrete fix for this issue yet.

**Comment by pete-otaqui** [comment]
I came across this problem when trying to install an express-based application on a machine with a clean NPM cache.

Note that cleaning the NPM cache on any machine demonstrated this error within my application.

I solved it by force-installing version `har-validator@v5.1.0` and saving that as a dev-dependency, which not only installed that version of the package, but updated my `package-lock.json` file.

**Comment by mklopets** [comment]
@DAlperin remove the package you're using that depends on node-har-validator & add it back. npm/yarn should resolve everything with the proper (existing) versions.

**Comment by tristanwagner** [comment]
Both removing package-lock.json or installing har-validator as a project dependency works for me.

**Comment by bongione** [comment]
While building node images with docker, I had to do force a cache clean on OS X, 

npm cache clean --force

then 
1) rm package-lock.json
2) npm i
3) re-run the docker build (with --no-cache for good measure)

**Comment by hielfx** [comment]
why would you do that...

**Comment by hwdsl2** [comment]
Just a heads up that the NPM repository returns inconsistent results for the unpublished 5.1.2 version. This command sometimes return 200, sometime return 404 Not Found:
```
curl -I https://registry.npmjs.org/har-validator/-/har-validator-5.1.2.tgz
```

**Comment by Daniel15** [comment]
@hwdsl2 It's likely that npm doesn't invalidate files on their CDN properly, and some CDN nodes still contain the old file.

**Comment by ilyaskarim** [comment]
We have node har validator issue on server deployment and fine on my local end. What is the possible issue?

**Comment by skimi** [comment]
> We have node har validator issue on server deployment and fine on my local end. What is the possible issue?

The version `5.1.2` seems to have been removed from npmjs. Locally you still have it. While deploying you fetch from npm.

**Comment by Shivendra30** [comment]
I am getting the following error even after installing har-validator

```
git push heroku master
Enumerating objects: 186, done.
Counting objects: 100% (186/186), done.
Delta compression using up to 4 threads
Compressing objects: 100% (166/166), done.
Writing objects: 100% (168/168), 315.09 KiB | 2.35 MiB/s, done.
Total 168 (delta 130), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  10.14.1
remote:        engines.npm (package.json):   6.4.1
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version 10.14.1...
remote:        Downloading and installing node 10.14.1...
remote:        npm 6.4.1 already installed with node
remote:        Resolving yarn version 1.x...
remote:        Downloading and installing yarn (1.12.3)...
remote:        Installed yarn 1.12.3
remote:
remote: -----> Restoring cache
remote:        Cached directories were not restored due to a change in version of node, npm, yarn or stack
remote:        Module installation may take longer for this build
remote:
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.12.3
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.2.4: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        [4/4] Building fresh packages...
remote:        Done in 7.46s.
remote:        Running heroku-postbuild (yarn)
remote:        yarn run v1.12.3
remote:        $ NPM_CONFIG_PRODUCTION=false npm install --prefix client && npmrun build --prefix client
remote: npm ERR! code ETARGET
remote: npm ERR! notarget No matching version found for har-validator@5.1.2
remote: npm ERR! notarget In most cases you or one of your dependencies are requesting
remote: npm ERR! notarget a package version that doesn't exist.
remote: npm ERR! notarget
remote: npm ERR! notarget It was specified as a dependency of 'admin'
remote: npm ERR! notarget
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /tmp/npmcache.Xspse/_logs/2018-12-06T16_28_30_672Z-debug.log
remote: error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentationabout this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to floating-wave-76653.
remote:
To https://git.heroku.com/floating-wave-76653.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/floating-wave-76653.git'

```

Here is my package.json:
```

{
  "name": "server",
  "version": "1.0.0",
  "description": "Backend API",
  "main": "server.js",
  "engines": {
    "node": "10.14.1",
    "npm": "6.4.1"
  },
  "scripts": {
    "start": "node server.js",
    "server": "nodemon server.js",
    "client-install": "npm install --prefix client",
    "client": "cd client && npm start",
    "dev": "concurrently \"npm run server\" \"npm run client\"",
    "heroku-postbuild": "NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client"
  },
  "author": "Shivendra",
  "license": "ISC",
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.18.3",
    "cors": "^2.8.5",
    "event-stream": "^3.3.4",
    "express": "^4.16.4",
    "jsonwebtoken": "^8.3.0",
    "jwt-decode": "^2.2.0",
    "mongoose": "^5.3.10",
    "nodemon": "^1.18.6",
    "passport": "^0.4.0",
    "passport-jwt": "^4.0.0",
    "validator": "^10.9.0"
  },
  "devDependencies": {
    "har-validator": "^5.1.3"
  }
}

```
Tried multiple times but I am still not able to push to heroku...

**Comment by dliuproduction** [comment]
> While building node images with docker, I had to do force a cache clean on OS X,
> 
> npm cache clean --force
> 
> then
> 
> 1. rm package-lock.json
> 2. npm i
> 3. re-run the docker build (with --no-cache for good measure)

Thanks for the insight, I'm having the same issue when deploying, and even after clearing the cache, npm is still looking for the 5.1.2 version of har-validator. Which version of node are you using for docker?

**Comment by Glathrop** [comment]
> I don't / can't support `yarn`, they seem to be doing their own snowflake thing ...
> 
> > for people using `yarn` because of the speed, `npm` has made massive improvements in recent versions and is actually faster than `yarn` now, see `npm ci`, `pacakge-lock.json`, `npm install` improvements, etc ...  _(just FYI)_
> 
> They also don't have any method of interacting with their registry to do things like unpublish: [yarnpkg/yarn#4746](https://github.com/yarnpkg/yarn/issues/4746)
> 
> unpublishing packages is part of the expected behavior of a registry, and of dependency management.
> 
> a registry or registry client does not take care of managing your dependencies for you, you still have to do your part in managing your dependencies in your apps.
> 
> @seprich also see these issues with Yarn that are going on unresolved: [yarnpkg/yarn#5212](https://github.com/yarnpkg/yarn/issues/5212)
> 
> I'm sorry, but `yarn` is not an official registry, and my packages (as well as all of npm's users packages) are targeted for publish on `npm`, which means we follow and support npm's workflows.

BTW This answer sucks.

**Comment by Glathrop** [comment]
From https://github.com/yarnpkg/yarn/issues/6694

https://github.com/yarnpkg/yarn/issues/6694#issuecomment-439710387

> I do not think I've done anything technically wrong in un-publishing, and if I have, I would love to learn "why" without waving into opinions on versioning and best practices.


> Anyone running yarn add something with something depending on your package will see it locked to the specific version locked when they first ran the tool. If you cause this package to become unavailable, they suddenly won't be able to install it, which can break their deployment workflow if they didn't use our offline mirror feature.
> 
> Unpublishing is imo a last-resort weapon that should never be used for simply patching bugs (which fixing the Node compatibility is), especially if your package has 35M downloads per month. It's almost guaranteed to cause pain to your users.

So now that Yarn has said that unpublishing was basically a mistake can you simply republish ? This was your own solution in that same thread.... kind seems like this has gone on long enough when you have an answer for it. 

> i'm tempted to just release a 5.1.2 and 5.1.1 duplicates of 5.1.0 to stop the noise. but honestly, I'm baffled to how broken the yarn process is here and how badly lock files are misunderstood! and most importantly this doesn't address the vuln / security warnings people are getting from deep nested dependencies.

**Comment by DanielRuf** [comment]
It seems .1 and .2 were removed which breaks setup. Was there a good reason to unpublish / remove them?

**Comment by DanielRuf** [comment]
It seems .1 and .2 were removed which breaks setups. Was there a good reason to unpublish / remove them?

**Comment by DanielRuf** [comment]
> Seems that the unpublishing has left yarn registry dirty.

yarnpkg is just a proxy for npmjs so this is not true. Yarn always uses the lockfile, `npm i` does not but `npm ci`.

**Comment by DanielRuf** [comment]
@pgonzal yarn and npm create tags when you use the `version` or `publish` commands but they are not pushed with `git push` but `git push --tags`.

**Comment by Glathrop** [comment]
@DanielRuf you are correct. Yarn is just a mirror. The primary issue can be resolved by deleting your lockfile and installing again using either system. 

The secondary issue which the author does not seem to want to correct is that the fix can cause more issues depending on your setup. Namely, you're likely signing up for a hunt and peck through your dependencies' sub-dependencies to make sure other package authors have updated their references to har-validator as well. 

If this were an infrequently used package it would not be that big a deal. At 520MM downloads a year it's a problem....

**Comment by DanielRuf** [comment]
@Glathrop no, a simple proxy, they both use Cloudflare and yarnpkg.com points to npmjs.com ;-) A mirror would be a copy on Yarn's side. (like a RAID mirror mode).

**Comment by Glathrop** [comment]
@DanielRuf and this is why I work on the front-end.

**Comment by felixcatto** [comment]
I removed package-lock.json, execute "npm i". Then cleared cache on heroku https://coderwall.com/p/jjcpra/clean-heroku-npm-cache
then i finally was able to push my changes on heroku without errors.

**Comment by Macil** [comment]
If you have a yarn.lock file referencing the since-unpublished version of har-validator, then removing your yarn.lock file and re-running `yarn` will fix your issues by generating a new yarn.lock file containing an existing version of har-validator. (Yarn works just like npm, just substitute "package-lock.json" for "yarn.lock", and "npm install" for "yarn".)

**Comment by motss** [comment]
I'm facing this weird issue on my machine with Windows 10 x64. I tried several time to rebuild the lockfile but for some unknown reasons, the `har-validator@5.1.2` was installed. I'm suspecting that might be due to the fact that `npm` is grabbing a cached version of `har-validator` from my local cache which is the unpublish `5.1.2`. I tried `npm cache clean --force` to clear the local NPM cache and it worked as NPM now grabbing whatever is the latest from the NPM registry.

Everyone can try this little finding of mine to see if it works for you.

**Comment by jamesgecko** [comment]
Yarn has a global lockfile. If this issue is preventing you from using `yarn global add`, you'll need to delete the file. It was in `~/.local/share/yarn/global/yarn.lock` on my macOS machine.

**Comment by taylorkline** [comment]
Deleting the global lockfile as @jamesgecko suggested worked for me, but the file was located at `~/.config/yarn/global/yarn.lock`

**Comment by ahmadnassri** [comment]
this library has not been maintained, nor has any further planned maintenance. I made a dependency update release today and this will be the last one. this repo will be archived.

**Comment by praveenpandey02** [comment]
> I'm investigating the issue, so far nobody has provided me with any reproducible steps.
> 
> `request` is dependant on version [`~5.1.0`](https://github.com/request/request/blob/master/package.json#L37)
> 
> `npm install request` correctly installs the latest matching version from npm:
> 
> ```
> $ npm install request
> $ npm list har-validator
> /tmp
> └─┬ request@2.88.0
>   └── har-validator@5.1.0
> ```
> 
> there was never any broken code pushed or changes made, other than bumping `ajv`, which, despite being a major version, still has no impact on `har-validator` or `request`

So this resolved my issue. I first ran `npm install request` and then proceeded further with other package installations.
