### ISSUE TITLE
Breaking change in a patch revision?

### ISSUE THREAD

**Issue by briiju** [ahmadnassri/node-har-validator#126]
From v5.1.0 to v5.1.1 there is an engine compatibility change. v5.1.1 no longer supports node v4 which has major implications for production systems. This is currently impacting one of my customers.

The npm library `request` at v2.88.1 is dependent on `har-validator` (~5.1.0). Har-validator has effectively broken `request` for node v4.

Please publish a 5.1.4 with node 4 compatibility and make a major version change in order to implement breaking changes.

**Comment by ahmadnassri** [comment]
this library has not been maintained, nor has any further planned maintenance. I made a dependency update release today and this will be the last one. this repo will be archived.
