### ISSUE TITLE
synk prototype pollution with ajv versions <6.12.3

### ISSUE THREAD

**Issue by skvijay007** [ahmadnassri/node-har-validator#169]
Security issue with ajv package < 6.12.3 with prototype pollution vulnerability

https://snyk.io/vuln/SNYK-JS-AJV-584908

Upgrade ajv to version 6.12.3 or higher.

**Comment by ahmadnassri** [comment]
new release is out with updated dependencies https://github.com/ahmadnassri/node-har-validator/releases/tag/v5.1.4
