### ISSUE TITLE
Is this project orphaned ?

### ISSUE THREAD

**Issue by rzr** [ahmadnassri/node-har-validator#196]
Hi,

I read that "This package has been deprecated"
from 
https://www.npmjs.com/package/har-validator# 

This project could be a good candidate for @abandonware co maintenance:

https://rzr.github.io/rzr-presentations//docs/abandonware/

Any internet to xfer this project to @abandonware org ?

Relate-to:  https://github.com/abandonware/abandonware.github.io/issues/5

**Comment by ahmadnassri** [comment]
this package is technically "feature complete", and aside from dependency updates (because security warnings) there is not much to improve / add / change in the functionality ...
